out_dir: results
metric_best: mae
metric_agg: argmin
num_workers: 4
mlflow:
  use: False
  project: Exp
  name: peptides-struct-GatedGCN-RWSE
wandb:
  use: True
  project: "PEGT"
  name: "peptides-struct-GatedGCN-RWSE"
  entity: jiaqing
dataset:
  format: OGB
  name: peptides-structural
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: Atom+RWSE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,21)
  model: Linear
  dim_pe: 16
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 128
  eval_period: 1
  ckpt_period: 100
model:
  type: custom_gnn
  loss_fun: l1
  graph_pooling: mean
gnn:
  layers_pre_mp: 0
  layers_mp: 5
  layers_post_mp: 1
  dim_inner: 208
  layer_type: gineconv
  act: relu
  residual: True
  dropout: 0.0
optim:
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 250
  scheduler: reduce_on_plateau
  reduce_factor: 0.5
  schedule_patience: 20
  min_lr: 1e-5