out_dir: results
metric_best: f1
wandb:
  use: True
  project: "PEGT"
  name: "COCO-MLP-LapPE"
  entity: jiaqing
dataset:
  dir: /tos-bjml-ai4chem/xiejiaqing/datasets/coco_superpixels_edge_wt_region_boundary
  format: PyG-COCOSuperpixels
  name: edge_wt_region_boundary
  slic_compactness: 30
  task: graph  # Even if VOC is node-level task, this needs to be set as 'graph'
  task_type: classification_multilabel
  transductive: False
  node_encoder: True
  node_encoder_name: COCONode+LapPE
  node_encoder_bn: False
  edge_encoder: False
  edge_encoder_name: COCOEdge
  edge_encoder_bn: False
posenc_LapPE:
  enable: True
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 10
  model: DeepSet
  dim_pe: 16
  layers: 2
  raw_norm_type: none
train:
  mode: custom
  batch_size: 50
  eval_period: 1
  ckpt_period: 100
  eval_smoothing_metrics: True
model:
  type: custom_gnn
  loss_fun: weighted_cross_entropy
gnn:
  head: inductive_node
  layers_pre_mp: 0
  layers_mp: 6
  layers_post_mp: 1
  dim_inner: 68
  batchnorm: True
  layer_type: mlpconv
  act: gelu
  dropout: 0.1
optim:
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.002
  max_epoch: 100
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10